# Configuration file for Field Services Agent API

# Default settings
defaults:
  tech_name: "Kyle Foley"
  date: "2025-09-04"

# API settings
api:
  host: "0.0.0.0"
  port: 8000
  debug: true

# Database settings (using CSV files)
database:
  type: "csv"
  files:
    work_orders: "Database/work_orders.csv"
    work_status_logs: "Database/work_status_logs.csv"
    completion_notes: "Database/completion_notes.csv"
    technicians: "Database/technicians.csv"
    work_status_types: "Database/work_status_types.csv"

# OpenAI settings
openai:
  model: "gpt-4o"
  max_tokens: 600
  temperature: 0.3

Work_Order_Type:
  Corrective:
    - Troubleshooting
    - Repairwork
    - Warrantysupport